AllCops:
  DisplayCopNames: true
  Exclude:
    - db/**
    - node_modules/**/**
    - config/**/**
    - bin/**
    - Gemfile
    - Rakefile
Rails:
  Enabled: true
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Style/ClassAndModuleChildren:
  Enabled: false
